/**
 * Image provenance extraction.
 *
 * Reads what an image's own bytes claim about how it was produced, in
 * descending order of authority:
 *
 *   1. C2PA Content Credentials  — cryptographically signed, hardest to forge
 *   2. IPTC DigitalSourceType    — the standard vocabulary, carried in XMP
 *   3. XMP / EXIF generator tags — advisory, trivially stripped or spoofed
 *   4. PNG text chunks           — where SD/ComfyUI stash their parameters
 *
 * A negative result means nothing. Shopify's image pipeline, most CDNs and
 * nearly every "export for web" path strip metadata, so an image with no
 * provenance is unresolved — never "not AI". That distinction is load-bearing:
 * it is why the engine sends unresolved images to a merchant for declaration
 * rather than quietly clearing them.
 */

import type { ContentOrigin, ProvenanceFinding, ProvenanceSource } from "./types";

/**
 * The IPTC DigitalSourceType vocabulary
 * (http://cv.iptc.org/newscodes/digitalsourcetype/), mapped onto our origins.
 *
 * ORDER IS SIGNIFICANT. These are matched as substrings and the terms nest:
 * "compositeWithTrainedAlgorithmicMedia" contains "trainedAlgorithmicMedia",
 * which itself ends with "algorithmicMedia". Most specific must come first or
 * a composite gets misread as a full generation, and a generation as a plain
 * algorithmic render.
 */
const DIGITAL_SOURCE_TYPES: ReadonlyArray<{
  token: string;
  origin: ContentOrigin;
  label: string;
}> = [
  {
    token: "compositewithtrainedalgorithmicmedia",
    origin: "ai_modified",
    label: "Edited with generative AI",
  },
  {
    token: "trainedalgorithmicmedia",
    origin: "ai_generated",
    label: "Created using generative AI",
  },
  {
    // Minor algorithmic enhancement — the assistive-editing case.
    token: "algorithmicallyenhanced",
    origin: "not_ai",
    label: "Algorithmically enhanced capture",
  },
  {
    token: "compositecapture",
    origin: "not_ai",
    label: "Composite of real captures",
  },
  {
    // Generated by an algorithm that was not trained on sampled data —
    // a fractal or a formula, not a generative model.
    token: "algorithmicmedia",
    origin: "not_ai",
    label: "Algorithmically created, not from a trained model",
  },
  { token: "digitalcapture", origin: "not_ai", label: "Digital capture" },
  { token: "negativefilm", origin: "not_ai", label: "Scanned negative film" },
  { token: "positivefilm", origin: "not_ai", label: "Scanned positive film" },
  { token: "print", origin: "not_ai", label: "Scanned print" },
  { token: "minorhumanedits", origin: "not_ai", label: "Capture with minor human edits" },
  { token: "virtualrecording", origin: "not_ai", label: "Virtual recording" },
  { token: "softwareimage", origin: "not_ai", label: "Software-produced image" },
];

/** Substrings that identify the tool that produced an image. */
const GENERATOR_FINGERPRINTS: ReadonlyArray<{ pattern: RegExp; name: string }> = [
  { pattern: /midjourney/i, name: "Midjourney" },
  { pattern: /dall[·`'’-]?e|openai/i, name: "DALL·E (OpenAI)" },
  { pattern: /adobe\s*firefly|firefly/i, name: "Adobe Firefly" },
  { pattern: /generative\s*fill|generative\s*expand/i, name: "Adobe Photoshop (Generative Fill)" },
  { pattern: /comfyui/i, name: "ComfyUI" },
  { pattern: /automatic1111|sd-?webui|stable\s*diffusion|stablediffusion/i, name: "Stable Diffusion" },
  { pattern: /black\s*forest|flux\.?1|\bflux\b/i, name: "FLUX (Black Forest Labs)" },
  { pattern: /imagen|gemini|google\s*ai/i, name: "Google Imagen / Gemini" },
  { pattern: /leonardo\.?ai/i, name: "Leonardo.Ai" },
  { pattern: /ideogram/i, name: "Ideogram" },
  { pattern: /runway/i, name: "Runway" },
  { pattern: /canva.*magic|magic\s*media/i, name: "Canva Magic Media" },
  { pattern: /nano\s*banana/i, name: "Nano Banana (Google)" },
  { pattern: /grok|xai/i, name: "Grok (xAI)" },
];

/**
 * Classifies a blob of metadata text against the IPTC vocabulary.
 * Returns null when no vocabulary term is present.
 */
export function classifyDigitalSourceType(
  text: string,
): { origin: ContentOrigin; token: string; label: string } | null {
  const haystack = text.toLowerCase();
  for (const entry of DIGITAL_SOURCE_TYPES) {
    if (haystack.includes(entry.token)) {
      return { origin: entry.origin, token: entry.token, label: entry.label };
    }
  }
  return null;
}

/** Names the generating tool from any metadata text, when recognisable. */
export function identifyGenerator(text: string): string | undefined {
  for (const { pattern, name } of GENERATOR_FINGERPRINTS) {
    if (pattern.test(text)) return name;
  }
  return undefined;
}

// --- container walkers -----------------------------------------------------

/** A named region of metadata pulled out of an image container. */
export interface MetadataSegment {
  kind: "exif" | "xmp" | "iptc" | "c2pa" | "text" | "unknown";
  /** Decoded text content, for substring matching. */
  text: string;
}

const ascii = (bytes: Uint8Array, start: number, length: number): string =>
  Array.from(bytes.subarray(start, start + length), (b) => String.fromCharCode(b)).join("");

/** True when the buffer starts with the JPEG SOI marker. */
export function isJpeg(bytes: Uint8Array): boolean {
  return bytes.length > 3 && bytes[0] === 0xff && bytes[1] === 0xd8;
}

/** True when the buffer starts with the 8-byte PNG signature. */
export function isPng(bytes: Uint8Array): boolean {
  const sig = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  return bytes.length >= sig.length && sig.every((b, i) => bytes[i] === b);
}

/** True when the buffer is a RIFF/WEBP container. */
export function isWebp(bytes: Uint8Array): boolean {
  // The RIFF header is exactly 12 bytes: "RIFF" + size + "WEBP".
  return (
    bytes.length >= 12 && ascii(bytes, 0, 4) === "RIFF" && ascii(bytes, 8, 4) === "WEBP"
  );
}

/**
 * Walks JPEG APP segments and returns the metadata-bearing ones.
 * Stops at SOS (start of scan) — everything after that is entropy-coded pixels.
 */
export function readJpegSegments(bytes: Uint8Array): MetadataSegment[] {
  const segments: MetadataSegment[] = [];
  let offset = 2; // skip SOI

  while (offset + 4 <= bytes.length) {
    if (bytes[offset] !== 0xff) break;
    const marker = bytes[offset + 1];

    // Standalone markers carry no length field.
    if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      offset += 2;
      continue;
    }
    // SOS: image data follows, nothing more to read.
    if (marker === 0xda || marker === 0xd9) break;

    const length = (bytes[offset + 2] << 8) | bytes[offset + 3];
    if (length < 2) break;
    const dataStart = offset + 4;
    const dataEnd = Math.min(dataStart + length - 2, bytes.length);
    const data = bytes.subarray(dataStart, dataEnd);

    if (marker === 0xe1) {
      // APP1: EXIF or XMP, distinguished by their namespace prefix.
      const header = ascii(data, 0, 30);
      if (header.startsWith("Exif")) {
        segments.push({ kind: "exif", text: decodeLoose(data) });
      } else if (header.includes("ns.adobe.com/xap")) {
        segments.push({ kind: "xmp", text: decodeLoose(data) });
      } else {
        segments.push({ kind: "unknown", text: decodeLoose(data) });
      }
    } else if (marker === 0xeb) {
      // APP11: JUMBF, which is how C2PA manifests ride along in a JPEG.
      segments.push({ kind: "c2pa", text: decodeLoose(data) });
    } else if (marker === 0xed) {
      // APP13: Photoshop IRB, carrier for legacy IPTC-IIM.
      segments.push({ kind: "iptc", text: decodeLoose(data) });
    } else if (marker === 0xfe) {
      segments.push({ kind: "text", text: decodeLoose(data) });
    }

    offset = dataEnd;
  }

  return segments;
}

/** Walks PNG chunks and returns the metadata-bearing ones. */
export function readPngChunks(bytes: Uint8Array): MetadataSegment[] {
  const segments: MetadataSegment[] = [];
  let offset = 8; // skip signature
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  while (offset + 8 <= bytes.length) {
    const length = view.getUint32(offset);
    const type = ascii(bytes, offset + 4, 4);
    const dataStart = offset + 8;
    if (dataStart + length > bytes.length) break;
    const data = bytes.subarray(dataStart, dataStart + length);

    switch (type) {
      case "tEXt":
      case "iTXt":
      case "zTXt":
        // Keyword and value are NUL-separated; loose decoding keeps both
        // searchable without needing to inflate zTXt/compressed iTXt.
        segments.push({ kind: "text", text: decodeLoose(data) });
        break;
      case "caBX":
        segments.push({ kind: "c2pa", text: decodeLoose(data) });
        break;
      case "eXIf":
        segments.push({ kind: "exif", text: decodeLoose(data) });
        break;
      case "IEND":
        return segments;
    }

    offset = dataStart + length + 4; // + CRC
  }

  return segments;
}

/** Walks RIFF/WebP chunks and returns the metadata-bearing ones. */
export function readWebpChunks(bytes: Uint8Array): MetadataSegment[] {
  const segments: MetadataSegment[] = [];
  let offset = 12; // RIFF + size + WEBP
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  while (offset + 8 <= bytes.length) {
    const type = ascii(bytes, offset, 4);
    const length = view.getUint32(offset + 4, true); // RIFF is little-endian
    const dataStart = offset + 8;
    if (dataStart + length > bytes.length) break;
    const data = bytes.subarray(dataStart, dataStart + length);

    if (type === "XMP ") segments.push({ kind: "xmp", text: decodeLoose(data) });
    else if (type === "EXIF") segments.push({ kind: "exif", text: decodeLoose(data) });

    // RIFF chunks are word-aligned.
    offset = dataStart + length + (length % 2);
  }

  return segments;
}

/** Dispatches to the right container walker. */
export function readMetadataSegments(bytes: Uint8Array): MetadataSegment[] {
  if (isJpeg(bytes)) return readJpegSegments(bytes);
  if (isPng(bytes)) return readPngChunks(bytes);
  if (isWebp(bytes)) return readWebpChunks(bytes);
  return [];
}

// --- the main entry point --------------------------------------------------

/**
 * Extracts a provenance finding from raw image bytes.
 *
 * Synchronous and dependency-free: everything it needs is a substring match
 * over decoded metadata regions. C2PA assertions are CBOR-encoded, but the
 * DigitalSourceType URIs appear verbatim as strings inside them, so scanning
 * for the vocabulary term is reliable without a CBOR decoder.
 */
export function parseProvenance(bytes: Uint8Array): ProvenanceFinding {
  const segments = readMetadataSegments(bytes);

  if (segments.length === 0) {
    return { source: "none", origin: "unknown" };
  }

  const raw: Record<string, unknown> = {
    segmentKinds: segments.map((s) => s.kind),
  };

  // 1. C2PA first — it is signed, so it outranks anything self-asserted.
  const c2paSegments = segments.filter((s) => s.kind === "c2pa");
  if (c2paSegments.length > 0) {
    const text = c2paSegments.map((s) => s.text).join("\n");
    raw.c2paPresent = true;
    const classified = classifyDigitalSourceType(text);
    const generator = identifyGenerator(text);
    if (classified) {
      raw.digitalSourceType = classified.token;
      raw.digitalSourceLabel = classified.label;
      return {
        source: "c2pa",
        origin: classified.origin,
        generatorName: generator,
        contentCreatedAt: extractDate(text),
        raw,
      };
    }
    // A manifest with no recognised source type still tells us a provenance
    // chain exists; the generator name may still identify it.
    if (generator) {
      return {
        source: "c2pa",
        origin: "ai_generated",
        generatorName: generator,
        contentCreatedAt: extractDate(text),
        raw: { ...raw, inferredFrom: "c2pa claim generator" },
      };
    }
  }

  // 2. IPTC DigitalSourceType carried in XMP.
  const xmpText = segments
    .filter((s) => s.kind === "xmp" || s.kind === "iptc")
    .map((s) => s.text)
    .join("\n");
  if (xmpText) {
    const classified = classifyDigitalSourceType(xmpText);
    if (classified) {
      raw.digitalSourceType = classified.token;
      raw.digitalSourceLabel = classified.label;
      return {
        source: "iptc",
        origin: classified.origin,
        generatorName: identifyGenerator(xmpText),
        contentCreatedAt: extractDate(xmpText),
        raw,
      };
    }
  }

  // 3. Fall back to generator fingerprints anywhere in the metadata. This is
  //    weak evidence — a filename or a prompt could mention a tool without the
  //    image coming from it — so it resolves to ai_generated but the merchant
  //    still sees it in review.
  const allText = segments.map((s) => s.text).join("\n");
  const generator = identifyGenerator(allText);
  if (generator) {
    const source: ProvenanceSource = xmpText ? "xmp" : "exif";
    return {
      source,
      origin: "ai_generated",
      generatorName: generator,
      contentCreatedAt: extractDate(allText),
      raw: { ...raw, inferredFrom: "generator fingerprint", confidence: "low" },
    };
  }

  // Metadata exists but says nothing about AI. Still unknown, not "not AI" —
  // an ordinary EXIF block proves a camera profile was written, not that no
  // generative step happened afterwards.
  return {
    source: "none",
    origin: "unknown",
    contentCreatedAt: extractDate(allText),
    raw,
  };
}

// --- helpers ---------------------------------------------------------------

/**
 * Decodes bytes to a searchable string, replacing NULs and control bytes with
 * spaces. Binary regions turn into noise rather than throwing, which is what
 * we want for substring scanning across mixed text/binary metadata.
 */
function decodeLoose(bytes: Uint8Array): string {
  let out = "";
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i];
    out += b >= 0x20 && b < 0x7f ? String.fromCharCode(b) : b === 0x0a ? "\n" : " ";
  }
  return out;
}

/** ISO-8601 or EXIF-style timestamps, whichever appears first. */
const ISO_DATE = /\b(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2}):(\d{2})/;
const EXIF_DATE = /\b(\d{4}):(\d{2}):(\d{2}) (\d{2}):(\d{2}):(\d{2})/;

function extractDate(text: string): Date | undefined {
  const iso = ISO_DATE.exec(text);
  if (iso) {
    const parsed = new Date(
      `${iso[1]}-${iso[2]}-${iso[3]}T${iso[4]}:${iso[5]}:${iso[6]}Z`,
    );
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  const exif = EXIF_DATE.exec(text);
  if (exif) {
    const parsed = new Date(
      `${exif[1]}-${exif[2]}-${exif[3]}T${exif[4]}:${exif[5]}:${exif[6]}Z`,
    );
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  return undefined;
}
